In [2]:
import pandas as pd
import numpy as np

### Accounts with issues sheet

In [25]:
issue_acc = pd.read_excel('MASTER_DATA.xlsx',sheet_name=0)
issue_acc.drop(columns=['Normalized Account Number','Account Number','CNBD 2','Site Code'],inplace=True)
issue_acc

,Provider Alias,Monitoring Status,Detailed,Detailed Status,Lapsed Days,Unnamed: 7,CircleName
0,BangaloreElectricitySupplyCoIND,PRODUCTION,nil,--,28.0,0,Karnataka
1,BangaloreElectricitySupplyCoIND,PRODUCTION,nil,--,17.0,0,Karnataka
2,BangaloreElectricitySupplyCoIND,PRODUCTION,nil,--,18.0,0,Karnataka
3,BangaloreElectricitySupplyCoIND,PRODUCTION,nil,--,24.0,0,Karnataka
4,BangaloreElectricitySupplyCoIND,PRODUCTION,nil,--,24.0,0,Karnataka
...,...,...,...,...,...,...,...
26977,TPWODLIND,PRODUCTION,nil,--,13.0,0,Orissa
26978,TPWODLIND,PRODUCTION,nil,--,13.0,0,Orissa
26979,TPWODLIND,PRODUCTION,nil,--,13.0,0,Orissa
26980,WESCOIND,INACTIVE,Since the invoice is not posted for more than ...,Since the invoice is not posted for more than ...,455.0,1,Orissa
26981,WESCOIND,INACTIVE,Since the invoice is not posted for more than ...,Since the invoice is not posted for more than ...,547.0,1,Orissa

In [26]:
issue_acc.rename(columns = {'Detailed Status':'DetailedStatus'}, inplace = True)
issue_acc

,Provider Alias,Monitoring Status,Detailed,DetailedStatus,Lapsed Days,Unnamed: 7,CircleName
0,BangaloreElectricitySupplyCoIND,PRODUCTION,nil,--,28.0,0,Karnataka
1,BangaloreElectricitySupplyCoIND,PRODUCTION,nil,--,17.0,0,Karnataka
2,BangaloreElectricitySupplyCoIND,PRODUCTION,nil,--,18.0,0,Karnataka
3,BangaloreElectricitySupplyCoIND,PRODUCTION,nil,--,24.0,0,Karnataka
4,BangaloreElectricitySupplyCoIND,PRODUCTION,nil,--,24.0,0,Karnataka
...,...,...,...,...,...,...,...
26977,TPWODLIND,PRODUCTION,nil,--,13.0,0,Orissa
26978,TPWODLIND,PRODUCTION,nil,--,13.0,0,Orissa
26979,TPWODLIND,PRODUCTION,nil,--,13.0,0,Orissa
26980,WESCOIND,INACTIVE,Since the invoice is not posted for more than ...,Since the invoice is not posted for more than ...,455.0,1,Orissa
26981,WESCOIND,INACTIVE,Since the invoice is not posted for more than ...,Since the invoice is not posted for more than ...,547.0,1,Orissa

In [7]:
issue_acc_final= issue_acc[(issue_acc.Detailed != 'nil')]
issue_acc_final.drop(columns=['Normalized Account Number','Account Number','CNBD 2','Site Code'],inplace=True)
issue_acc_final

D:\anaconda\lib\site-packages\pandas\core\frame.py:4308: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().drop(

,Provider Alias,Monitoring Status,Detailed,DetailedStatus,Lapsed Days,Unnamed: 7,CircleName
55,BangaloreElectricitySupplyCoIND,INACTIVE,Since the invoice is not posted for more than ...,Since the invoice is not posted for more than ...,589.0,1,Karnataka
190,BangaloreElectricitySupplyCoIND,INACTIVE,Since the invoice is not posted for more than ...,Since the invoice is not posted for more than ...,148.0,1,Karnataka
191,BangaloreElectricitySupplyCoIND,INACTIVE,Since the invoice is not posted for more than ...,Since the invoice is not posted for more than ...,601.0,1,Karnataka
303,BangaloreElectricitySupplyCoIND,INACTIVE,Since the invoice is not posted for more than ...,Since the invoice is not posted for more than ...,140.0,1,Karnataka
314,BangaloreElectricitySupplyCoIND,INACTIVE,Since the invoice is not posted for more than ...,Since the invoice is not posted for more than ...,148.0,1,Karnataka
...,...,...,...,...,...,...,...
26744,TPWODLIND,INACTIVE,Since the invoice is not posted for more than ...,Since the invoice is not posted for more than ...,199.0,1,Orissa
26753,TPWODLIND,INACTIVE,Since the invoice is not posted for more than ...,Since the invoice is not posted for more than ...,199.0,1,Orissa
26762,TPWODLIND,INACTIVE,Since the invoice is not posted for more than ...,Since the invoice is not posted for more than ...,199.0,1,Orissa
26980,WESCOIND,INACTIVE,Since the invoice is not posted for more than ...,Since the invoice is not posted for more than ...,455.0,1,Orissa
26981,WESCOIND,INACTIVE,Since the invoice is not posted for more than ...,Since the invoice is not posted for more than ...,547.0,1,Orissa

### Delivery failures

In [29]:
del_fail_sheet = pd.read_excel('OCT Json.xlsx',sheet_name=0)
del_fail_sheet.drop(columns=['StatementId','AccountNumber','SiteCode'],inplace=True)
del_fail_sheet

,Date,ProviderAlias,Circle,Statementdate,DeliveryResult,ResponseCode,ResponseBody,Unnamed: 10,Unnamed: 11,Unnamed: 12
0,01.10.2021,MPPaschimKshetraVidyutVitaranCoIND,MadhyaPradesh,2021-09-29,NOT_WANTED_API_REJECTED,400,"{""message"":""No EB Master found for SiteId/Cons...",code:400,"type:""ERROR""","details:""No Match on Consumer Number: CLZ49 - ..."
1,01.10.2021,MaharashtraStateElectricityDistributionIND,Maharashtra,2021-09-29,NOT_WANTED_API_REJECTED,400,"{""message"":""No EB Master defined for SiteId""",code:400,"type:""ERROR""","details:""SiteId: 587476""}'"
2,01.10.2021,MPPaschimKshetraVidyutVitaranCoIND,MadhyaPradesh,2021-09-29,NOT_WANTED_API_REJECTED,400,"{""message"":""No EB Master found for SiteId/Cons...",code:400,"type:""ERROR""","details:""No Match on Consumer Number: BDD26-34..."
3,01.10.2021,MPPaschimKshetraVidyutVitaranCoIND,MadhyaPradesh,2021-09-29,NOT_WANTED_API_REJECTED,400,"{""message"":""No EB Master found for SiteId/Cons...",code:400,"type:""ERROR""","details:""No Match on Consumer Number: MSZ22 - ..."
4,01.10.2021,MPPaschimKshetraVidyutVitaranCoIND,MadhyaPradesh,2021-09-28,NOT_WANTED_API_REJECTED,400,"{""message"":""No EB Master found for SiteId/Cons...",code:400,"type:""ERROR""","details:""No Match on Consumer Number: MLZ84 - ..."
...,...,...,...,...,...,...,...,...,...,...
3589,29.10.2021,TamilNaduElectricityBoardIND,TamilNadu,2021-10-28,NOT_WANTED_API_REJECTED,400,"{""message"":""No EB Master found for SiteId/Cons...",code:400,"type:""ERROR""","details:""No Match on Consumer Number: 05172016..."
3590,29.10.2021,MPPaschimKshetraVidyutVitaranCoIND,MadhyaPradesh,2021-10-28,NOT_WANTED_API_REJECTED,400,"{""message"":""No EB Master found for SiteId/Cons...",code:400,"type:""ERROR""","details:""No Match on Consumer Number: Ã¯Â¿Â½34246..."
3591,29.10.2021,TamilNaduElectricityBoardIND,TamilNadu,2021-10-28,NOT_WANTED_API_REJECTED,400,"{""message"":""No EB Master defined for SiteId""",code:400,"type:""ERROR""","details:""SiteId: 587295""}"
3592,29.10.2021,TheBrihanmumbaiElectricSupplyAndTransportIND,Mumbai,2021-10-28,NOT_WANTED_API_REJECTED,400,"{""message"":""No EB Master found for SiteId/Cons...",code:400,"type:""ERROR""","details:""No Match on Consumer Number: 32328900..."
3593,29.10.2021,TheBrihanmumbaiElectricSupplyAndTransportIND,Mumbai,2021-10-28,NOT_WANTED_API_REJECTED,400,"{""message"":""No EB Master found for SiteId/Cons...",code:400,"type:""ERROR""","details:""No Match on Consumer Number: 799-437-..."

In [10]:
del_fail_sheet["Statementdate"] = pd.to_datetime(del_fail_sheet["Statementdate"])  
date_range = (del_fail_sheet["Statementdate"] >= "2021-10-01") & (del_fail_sheet["Statementdate"] <= "2021-10-29") & (del_fail_sheet["Date"] >= "01.10.2021") & (del_fail_sheet["Date"] <= "29.10.2021")
temp_df1=del_fail_sheet.loc[date_range]
del_fail_final = temp_df1[['Date','ProviderAlias','Circle','Statementdate','DeliveryResult','ResponseCode','ResponseBody']]
del_fail_final

,Date,ProviderAlias,Circle,Statementdate,DeliveryResult,ResponseCode,ResponseBody
19,01.10.2021,GoaElectricityDeptIND,Maharashtra,2021-10-01,NOT_WANTED_API_REJECTED,400,"{""message"":""No EB Master found for SiteId/Cons..."
20,01.10.2021,GoaElectricityDeptIND,Maharashtra,2021-10-01,NOT_WANTED_API_DUPLICATE,409,"{""message"":""EB Feed details already exists - S..."
124,04.10.2021,GulbargaElectricitySupplyCompanyIND,Karnataka,2021-10-01,NOT_WANTED_API_REJECTED,400,"{""message"":""No EB Master found for SiteId/Cons..."
125,04.10.2021,GulbargaElectricitySupplyCompanyIND,Karnataka,2021-10-01,NOT_WANTED_API_REJECTED,400,"{""message"":""No EB Master found for SiteId/Cons..."
131,04.10.2021,GulbargaElectricitySupplyCompanyIND,Karnataka,2021-10-03,NOT_WANTED_API_REJECTED,400,"{""message"":""No EB Master found for SiteId/Cons..."
...,...,...,...,...,...,...,...
3589,29.10.2021,TamilNaduElectricityBoardIND,TamilNadu,2021-10-28,NOT_WANTED_API_REJECTED,400,"{""message"":""No EB Master found for SiteId/Cons..."
3590,29.10.2021,MPPaschimKshetraVidyutVitaranCoIND,MadhyaPradesh,2021-10-28,NOT_WANTED_API_REJECTED,400,"{""message"":""No EB Master found for SiteId/Cons..."
3591,29.10.2021,TamilNaduElectricityBoardIND,TamilNadu,2021-10-28,NOT_WANTED_API_REJECTED,400,"{""message"":""No EB Master defined for SiteId"""
3592,29.10.2021,TheBrihanmumbaiElectricSupplyAndTransportIND,Mumbai,2021-10-28,NOT_WANTED_API_REJECTED,400,"{""message"":""No EB Master found for SiteId/Cons..."
3593,29.10.2021,TheBrihanmumbaiElectricSupplyAndTransportIND,Mumbai,2021-10-28,NOT_WANTED_API_REJECTED,400,"{""message"":""No EB Master found for SiteId/Cons..."

In [50]:
del_fail_pivot = pd.pivot_table(del_fail_final, values='StatementId', index=['Circle','ProviderAlias'],
                    aggfunc={'StatementId': ['count']})
del_fail_pivot

                                                            count
Circle        ProviderAlias
AndhraPradesh EPDCAPIND                                        94
Chhattisgarh  ChhattisgarhStatePowerDistributionCOIND          93
Karnataka     BangaloreElectricitySupplyCoIND                  12
              ChamundeshwariElectricitySupplyCorpIND           10
              GulbargaElectricitySupplyCompanyIND              22
              HubliElectricitySupplyCoIND                      12
Kerala        KSEBIND                                          81
MadhyaPradesh MPMadhyaKshetraVidyutVitaranCoIND               811
              MPPaschimKshetraVidyutVitaranCoIND              247
              MPPoorvKshetraVidyutVitaranIND                 1530
Maharashtra   GoaElectricityDeptIND                            21
              MaharashtraStateElectricityDistributionIND       90
              TorrentPowerLimitedIND                           16
Mumbai        MaharashtraStateElectricityDistributionIND       51
              TataPowerIND                                      1
              TheBrihanmumbaiElectricSupplyAndTransportIND     31
              TorrentPowerLimitedIND                           17
Orissa        TPCODLIND                                         6
              TPNODLIND                                        57
              TPSODLIND                                         2
              TPWODLIND                                       145
TamilNadu     TamilNaduElectricityBoardIND                     54

In [51]:
del_fail_pivot['count'].sum()

3403

In [30]:
# cust_data = pd.read_csv('ebfeed_dump.csv')
# cust_data

D:\anaconda\lib\site-packages\IPython\core\interactiveshell.py:3165: DtypeWarning: Columns (61) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,

,Site ID,Consumer ID,Meter No (KWH),Old Account No,Knumber,Phase,Sanctioned Load,Meter Status,Tariff,Board Name,...,FeedStatus,Transformer Loss Unit,Rebate Unit,Penalty Units,Total Units,Circle,Unnamed: 147,Unnamed: 148,Unnamed: 149,Unnamed: 150
0,509207,065630091131,1592002,NaN,NaN,THREE,15.00,NORMAL,LM51,TamilNaduElectricityBoardIND,...,NEW,-,-,-,"5,250",IND Tamilnadu,NaN,NaN,NaN,NaN
1,549682,2355223000,6408557721,NaN,NaN,NaN,18.00,NaN,1LT3IN,BangaloreElectricitySupplyCoIND,...,NEW,-,-,-,"1,480",IND Karnataka,NaN,NaN,NaN,NaN
2,462389,TNZ51 - 17 - 3376027613,GENUS3915200,IT51 - 17 - 7408124000,NaN,THREE,16.00,NORMAL,LV2.2,MPPaschimKshetraVidyutVitaranCoIND,...,NEW,-,-,-,0,IND Madhya Pradesh,NaN,NaN,NaN,NaN
3,591742,160263887473,08806766415,NaN,4613,NaN,3.00,NaN,052 / LT-II COMM < 20KW,MaharashtraStateElectricityDistributionIND,...,VALIDATED,-,-,-,"1,929",IND Maharashtra,NaN,NaN,NaN,NaN
4,462452,3615105-GHS11-2-N3105008765,SECUREMPP20902,11-2-83227,NaN,THREE,16.00,NORMAL,LV2.2,MPPaschimKshetraVidyutVitaranCoIND,...,NEW,-,-,-,"5,091",IND Madhya Pradesh,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
23131,530846,3634415-TNL1-30-N3435022400,SECUREMPP30859,1 - 30 - 7481,NaN,THREE,15.00,NORMAL,LV2.2,MPPaschimKshetraVidyutVitaranCoIND,...,NEW,-,-,-,"3,943",IND Madhya Pradesh,NaN,NaN,NaN,NaN
23132,461238,3363302-NLT95-50-N3332007082,AVON3089407,95 - 50 - 120455,NaN,THREE,15.00,NORMAL,LV2.2,MPPaschimKshetraVidyutVitaranCoIND,...,NEW,-,-,-,"1,990",IND Madhya Pradesh,NaN,NaN,NaN,NaN
23133,570633,3634408-MGN1-4-N3428028882,GENUS9015717,1 - 4 - 3440,NaN,THREE,15.00,NORMAL,LV2.2,MPPaschimKshetraVidyutVitaranCoIND,...,NEW,-,-,-,"4,603",IND Madhya Pradesh,NaN,NaN,NaN,NaN
23134,544954,1165172026491,L+G065170004961581,NaN,NaN,THREE,8.22,Working,LT-6F,KSEBIND,...,NEW,-,-,-,"2,920",IND Kerala,NaN,NaN,NaN,NaN
23135,545763,1166644020360,L&T001860018327073,NaN,NaN,THREE,15.89,Working,LT-6F,KSEBIND,...,NEW,-,-,-,0,IND Kerala,NaN,NaN,NaN,NaN

In [12]:
# cust_data["Concatenate"]=cust_data["Board Name"]+'-'+cust_data["Site ID"].astype(str)
# cust_data

In [13]:
cust_data["Bill Issue Date"] = pd.to_datetime(cust_data["Bill Issue Date"])  
date_range = (cust_data["Bill Issue Date"] >= "2021-10-01") & (cust_data["Bill Issue Date"] <= "2021-11-01")
cust_data_final=cust_data.loc[date_range]
cust_data_final
final_cust_df = cust_data_final[['Board Name','Bill Issue Date','Created Date','Circle']]
final_cust_df

,Board Name,Bill Issue Date,Created Date,Circle
292,GoaElectricityDeptIND,2021-10-01,2021-09-27,IND Maharashtra
595,GoaElectricityDeptIND,2021-10-01,2021-09-28,IND Maharashtra
738,GoaElectricityDeptIND,2021-10-01,2021-09-29,IND Maharashtra
1054,GoaElectricityDeptIND,2021-10-01,2021-09-30,IND Maharashtra
1060,GoaElectricityDeptIND,2021-10-04,2021-09-30,IND Maharashtra
...,...,...,...,...
23131,MPPaschimKshetraVidyutVitaranCoIND,2021-10-28,2021-10-29,IND Madhya Pradesh
23132,MPPaschimKshetraVidyutVitaranCoIND,2021-10-28,2021-10-29,IND Madhya Pradesh
23133,MPPaschimKshetraVidyutVitaranCoIND,2021-10-28,2021-10-29,IND Madhya Pradesh
23134,KSEBIND,2021-10-28,2021-10-29,IND Kerala
23135,KSEBIND,2021-10-28,2021-10-29,IND Kerala

In [56]:
cust_acc_table_final = pd.pivot_table(final_cust_df, values='Site ID', index=['Circle','Board Name'],
                    aggfunc={'Site ID': ['count','nunique']})
cust_acc_table_final

                                                                 count  \
Circle             Board Name
IND Andhra Pradesh EPDCAPIND                                       506
IND Karnataka      BangaloreElectricitySupplyCoIND                2059
                   ChamundeshwariElectricitySupplyCorpIND          240
                   GulbargaElectricitySupplyCompanyIND             307
                   HubliElectricitySupplyCoIND                     506
                   MangaloreElectricitySupplyCOIND                 211
IND Kerala         KSEBIND                                        1695
IND Madhya Pradesh ChhattisgarhStatePowerDistributionCOIND        1688
                   MPMadhyaKshetraVidyutVitaranCoIND              1416
                   MPPaschimKshetraVidyutVitaranCoIND             1360
                   MPPoorvKshetraVidyutVitaranIND                  341
IND Maharashtra    GoaElectricityDeptIND                           100
                   MaharashtraStateElectricityDistributionIND     5812
                   TorrentPowerLimitedIND                           53
IND Mumbai Circle  KSEBIND                                           1
                   MaharashtraStateElectricityDistributionIND      561
                   TataPowerIND                                     13
                   TheBrihanmumbaiElectricSupplyAndTransportIND    172
                   TorrentPowerLimitedIND                           41
IND Orissa         TPCODLIND                                      1389
                   TPNODLIND                                       773
                   TPSODLIND                                       395
                   TPWODLIND                                       586
IND Tamilnadu      TamilNaduElectricityBoardIND                   1364

                                                                 nunique
Circle             Board Name
IND Andhra Pradesh EPDCAPIND                                         502
IND Karnataka      BangaloreElectricitySupplyCoIND                  2033
                   ChamundeshwariElectricitySupplyCorpIND            235
                   GulbargaElectricitySupplyCompanyIND               301
                   HubliElectricitySupplyCoIND                       497
                   MangaloreElectricitySupplyCOIND                   206
IND Kerala         KSEBIND                                          1692
IND Madhya Pradesh ChhattisgarhStatePowerDistributionCOIND          1651
                   MPMadhyaKshetraVidyutVitaranCoIND                1380
                   MPPaschimKshetraVidyutVitaranCoIND               1335
                   MPPoorvKshetraVidyutVitaranIND                    334
IND Maharashtra    GoaElectricityDeptIND                              98
                   MaharashtraStateElectricityDistributionIND       5812
                   TorrentPowerLimitedIND                             53
IND Mumbai Circle  KSEBIND                                             1
                   MaharashtraStateElectricityDistributionIND        561
                   TataPowerIND                                       13
                   TheBrihanmumbaiElectricSupplyAndTransportIND      172
                   TorrentPowerLimitedIND                             41
IND Orissa         TPCODLIND                                        1372
                   TPNODLIND                                         773
                   TPSODLIND                                         395
                   TPWODLIND                                         586
IND Tamilnadu      TamilNaduElectricityBoardIND                     1363

In [57]:
cust_acc_table_final.rename(columns = {'count':'All',
                                        'nunique':'Unique'}, inplace = True)
cust_acc_table_final

                                                                  All  Unique
Circle             Board Name
IND Andhra Pradesh EPDCAPIND                                      506     502
IND Karnataka      BangaloreElectricitySupplyCoIND               2059    2033
                   ChamundeshwariElectricitySupplyCorpIND         240     235
                   GulbargaElectricitySupplyCompanyIND            307     301
                   HubliElectricitySupplyCoIND                    506     497
                   MangaloreElectricitySupplyCOIND                211     206
IND Kerala         KSEBIND                                       1695    1692
IND Madhya Pradesh ChhattisgarhStatePowerDistributionCOIND       1688    1651
                   MPMadhyaKshetraVidyutVitaranCoIND             1416    1380
                   MPPaschimKshetraVidyutVitaranCoIND            1360    1335
                   MPPoorvKshetraVidyutVitaranIND                 341     334
IND Maharashtra    GoaElectricityDeptIND                          100      98
                   MaharashtraStateElectricityDistributionIND    5812    5812
                   TorrentPowerLimitedIND                          53      53
IND Mumbai Circle  KSEBIND                                          1       1
                   MaharashtraStateElectricityDistributionIND     561     561
                   TataPowerIND                                    13      13
                   TheBrihanmumbaiElectricSupplyAndTransportIND   172     172
                   TorrentPowerLimitedIND                          41      41
IND Orissa         TPCODLIND                                     1389    1372
                   TPNODLIND                                      773     773
                   TPSODLIND                                      395     395
                   TPWODLIND                                      586     586
IND Tamilnadu      TamilNaduElectricityBoardIND                  1364    1363

In [58]:
cust_acc_table_final['All'].sum()

21589

In [59]:
cust_acc_table_final['Unique'].sum()

21406

In [60]:
def dfs_tabs(df_list, sheet_list, file_name):
    writer = pd.ExcelWriter(file_name,engine='xlsxwriter')   
    for dataframe, sheet in zip(df_list, sheet_list):
        dataframe.to_excel(writer, sheet_name=sheet, startrow=0 , startcol=0)   
    writer.save()


dfs = [issue_acc_final,del_fail_final,del_fail_pivot,final_cust_df,cust_acc_table_final]
sheets = ['Accounts with issues','Delivery Failures',
          'delivery_failures_pivot','Customer portal accounts','cust_acc_portal_pivot']    


dfs_tabs(dfs, sheets, 'Final file using python.xlsx')

In [33]:
del_fail_sheet = pd.read_excel('NOV Json.xlsx',sheet_name=0)
del_fail_sheet.drop(columns=['StatementId','AccountNumber','SiteCode'],inplace=True)
del_fail_sheet

,Date,Delivered Date,ProviderAlias,Circle,Statementdate,DeliveryResult,ResponseCode,ResponseBody,Unnamed: 11,Unnamed: 12,Unnamed: 13
0,29.10.2021,11.01.2021,MaharashtraStateElectricityDistributionIND,Mumbai,2021-10-28,NOT_WANTED_API_REJECTED,400,"{""message"":""No EB Master found for SiteId/Cons...",code:400,"type:""ERROR""","details:""No Match on Consumer Number: 00033422..."
1,29.10.2021,11.01.2021,MaharashtraStateElectricityDistributionIND,Mumbai,2021-10-28,NOT_WANTED_API_REJECTED,400,"{""message"":""No EB Master defined for SiteId""",code:400,"type:""ERROR""","details:""SiteId: 587428""}"
2,29.10.2021,11.01.2021,TheBrihanmumbaiElectricSupplyAndTransportIND,Mumbai,2021-10-29,NOT_WANTED_API_REJECTED,400,"{""message"":""No EB Master found for SiteId/Cons...",code:400,"type:""ERROR""","details:""No Match on Consumer Number: 904624602""}"
3,29.10.2021,11.01.2021,TheBrihanmumbaiElectricSupplyAndTransportIND,Mumbai,2021-10-29,NOT_WANTED_API_REJECTED,400,"{""message"":""No EB Master found for SiteId/Cons...",code:400,"type:""ERROR""","details:""No Match on Consumer Number: 90880281..."
4,29.10.2021,11.01.2021,TheBrihanmumbaiElectricSupplyAndTransportIND,Mumbai,2021-10-29,NOT_WANTED_API_REJECTED,400,"{""message"":""No EB Master found for SiteId/Cons...",code:400,"type:""ERROR""","details:""No Match on Consumer Number: 50430297..."
...,...,...,...,...,...,...,...,...,...,...,...
151,04.11.2021,05.11.2021,EPDCAPIND,AndhraPradesh,2021-11-03,NOT_WANTED_API_REJECTED,400,"{""message"":""No EB Master found for SiteId/Cons...",code:400,"type:""ERROR""","details:""No Match on Consumer Number: \""112312..."
152,04.11.2021,05.11.2021,MaharashtraStateElectricityDistributionIND,Maharashtra,2021-11-04,NOT_WANTED_API_REJECTED,400,"{""message"":""No EB Master found for SiteId/Cons...",code:400,"type:""ERROR""","details:""No Match on Consumer Number: 17001908..."
153,04.11.2021,05.11.2021,KSEBIND,Kerala,2021-11-01,NOT_WANTED_API_REJECTED,400,"{""message"":""No EB Master found for SiteId/Cons...",code:400,"type:""ERROR""","details:""No Match on Consumer Number: 33461""}'"
154,04.11.2021,05.11.2021,KSEBIND,Kerala,2021-11-01,NOT_WANTED_API_REJECTED,404,"{""message"":""site with id 591368 not found""",code:404,"type:""ERROR""",details:null}'
155,04.11.2021,05.11.2021,KSEBIND,Kerala,2021-11-01,NOT_WANTED_API_REJECTED,404,"{""message"":""site with id 588006 not found""",code:404,"type:""ERROR""",details:null}'

In [15]:
del_fail_sheet["Statementdate"] = pd.to_datetime(del_fail_sheet["Statementdate"])  
date_range = (del_fail_sheet["Statementdate"] >= "2021-11-01") & (del_fail_sheet["Statementdate"] <= "2021-11-05")
temp_df1=del_fail_sheet.loc[date_range]
del_fail_final = temp_df1[['Date','ProviderAlias','Circle','Statementdate','DeliveryResult','ResponseCode','ResponseBody']]
del_fail_final

,Date,ProviderAlias,Circle,Statementdate,DeliveryResult,ResponseCode,ResponseBody
63,01.11.2021,GulbargaElectricitySupplyCompanyIND,Karnataka,2021-11-01,NOT_WANTED_API_REJECTED,400,"{""message"":""No EB Master found for SiteId/Cons..."
64,01.11.2021,KSEBIND,Kerala,2021-11-01,NOT_WANTED_API_REJECTED,404,"{""message"":""site with id 595518 not found"""
65,01.11.2021,KSEBIND,Kerala,2021-11-01,NOT_WANTED_API_REJECTED,400,"{""message"":""No EB Master found for SiteId/Cons..."
66,01.11.2021,KSEBIND,Kerala,2021-11-01,NOT_WANTED_API_REJECTED,404,"{""message"":""site with id 587947 not found"""
67,01.11.2021,KSEBIND,Kerala,2021-11-01,NOT_WANTED_API_REJECTED,404,"{""message"":""site with id 593808 not found"""
...,...,...,...,...,...,...,...
151,04.11.2021,EPDCAPIND,AndhraPradesh,2021-11-03,NOT_WANTED_API_REJECTED,400,"{""message"":""No EB Master found for SiteId/Cons..."
152,04.11.2021,MaharashtraStateElectricityDistributionIND,Maharashtra,2021-11-04,NOT_WANTED_API_REJECTED,400,"{""message"":""No EB Master found for SiteId/Cons..."
153,04.11.2021,KSEBIND,Kerala,2021-11-01,NOT_WANTED_API_REJECTED,400,"{""message"":""No EB Master found for SiteId/Cons..."
154,04.11.2021,KSEBIND,Kerala,2021-11-01,NOT_WANTED_API_REJECTED,404,"{""message"":""site with id 591368 not found"""
155,04.11.2021,KSEBIND,Kerala,2021-11-01,NOT_WANTED_API_REJECTED,404,"{""message"":""site with id 588006 not found"""