In [2]:
import pandas as pd
import numpy as np

### Accounts with issues sheet

In [2]:
acc_with_issues = pd.read_excel('ATC_MTD Dashboard_till Oct01-Oct29.xlsx',sheet_name=1)
acc_with_issues

,Normalized Account Number,Account Number,Provider Alias,Monitoring Status,Detailed Status,Site Code,CNBD 2,CircleName
0,1210749222,1210749222,BangaloreElectricitySupplyCoIND,INACTIVE,Since the invoice is not posted for more than ...,588720,9794689077,Karnataka
1,1867207000,1867207000,BangaloreElectricitySupplyCoIND,INACTIVE,Since the invoice is not posted for more than ...,551605,1867207000,Karnataka
2,1881365201,1881365201,BangaloreElectricitySupplyCoIND,INACTIVE,Since the invoice is not posted for more than ...,585096,1341011564,Karnataka
3,2151207000,2151207000,BangaloreElectricitySupplyCoIND,INACTIVE,Since the invoice is not posted for more than ...,551054,2151207000,Karnataka
4,2174996000,2174996000,BangaloreElectricitySupplyCoIND,INACTIVE,Since the invoice is not posted for more than ...,550465,2174996000,Karnataka
...,...,...,...,...,...,...,...,...
526,813001110327,813001110327,TPWODLIND,INACTIVE,Since the invoice is not posted for more than ...,568983,NaN,Orissa
527,813001110378,813001110378,TPWODLIND,INACTIVE,Since the invoice is not posted for more than ...,453636,NaN,Orissa
528,813001110468,813001110468,TPWODLIND,INACTIVE,Since the invoice is not posted for more than ...,571767,NaN,Orissa
529,416001110318,4160 0111 0318,WESCOIND,INACTIVE,Since the invoice is not posted for more than ...,508434,NaN,Orissa
530,911001060286,9110 0106 0286,WESCOIND,INACTIVE,Since the invoice is not posted for more than ...,454203,NaN,Orissa

In [15]:
issue_acc = pd.read_excel('MASTER_DATA.xlsx',sheet_name=0)
issue_acc

## the 'Detailed' status needs to be made manually

,Normalized Account Number,Account Number,Provider Alias,Monitoring Status,Detailed,Detailed Status,Lapsed Days,Unnamed: 7,CircleName,CNBD 2,Site Code
0,1000705000,1000705000,BangaloreElectricitySupplyCoIND,PRODUCTION,nil,--,28.0,0,Karnataka,1000705000,551066
1,1002523,1002523,BangaloreElectricitySupplyCoIND,PRODUCTION,nil,--,17.0,0,Karnataka,1002523,500240
2,1013617000,1013617000,BangaloreElectricitySupplyCoIND,PRODUCTION,nil,--,18.0,0,Karnataka,1013617000,550341
3,1016418000,1016418000,BangaloreElectricitySupplyCoIND,PRODUCTION,nil,--,24.0,0,Karnataka,1016418000,551558
4,1016800000,1016800000,BangaloreElectricitySupplyCoIND,PRODUCTION,nil,--,24.0,0,Karnataka,1016800000,551532
...,...,...,...,...,...,...,...,...,...,...,...
26977,915001110463,915001110463,TPWODLIND,PRODUCTION,nil,--,13.0,0,Orissa,NaN,525101
26978,915001110464,915001110464,TPWODLIND,PRODUCTION,nil,--,13.0,0,Orissa,NaN,525133
26979,915001110465,915001110465,TPWODLIND,PRODUCTION,nil,--,13.0,0,Orissa,NaN,525115
26980,416001110318,4160 0111 0318,WESCOIND,INACTIVE,Since the invoice is not posted for more than ...,Since the invoice is not posted for more than ...,455.0,1,Orissa,NaN,508434
26981,911001060286,9110 0106 0286,WESCOIND,INACTIVE,Since the invoice is not posted for more than ...,Since the invoice is not posted for more than ...,547.0,1,Orissa,NaN,454203

In [11]:
issue_acc.rename(columns = {'Detailed Status':'DetailedStatus'}, inplace = True)
issue_acc

,Normalized Account Number,Account Number,Provider Alias,Monitoring Status,DetailedStatus,Lapsed Days,Unnamed: 6,CircleName,CNBD 2,Site Code
0,1000705000,1000705000,BangaloreElectricitySupplyCoIND,PRODUCTION,--,28.0,0,Karnataka,1000705000,551066
1,1002523,1002523,BangaloreElectricitySupplyCoIND,PRODUCTION,--,17.0,0,Karnataka,1002523,500240
2,1013617000,1013617000,BangaloreElectricitySupplyCoIND,PRODUCTION,--,18.0,0,Karnataka,1013617000,550341
3,1016418000,1016418000,BangaloreElectricitySupplyCoIND,PRODUCTION,--,24.0,0,Karnataka,1016418000,551558
4,1016800000,1016800000,BangaloreElectricitySupplyCoIND,PRODUCTION,--,24.0,0,Karnataka,1016800000,551532
...,...,...,...,...,...,...,...,...,...,...
26977,915001110463,915001110463,TPWODLIND,PRODUCTION,--,13.0,0,Orissa,NaN,525101
26978,915001110464,915001110464,TPWODLIND,PRODUCTION,--,13.0,0,Orissa,NaN,525133
26979,915001110465,915001110465,TPWODLIND,PRODUCTION,--,13.0,0,Orissa,NaN,525115
26980,416001110318,4160 0111 0318,WESCOIND,INACTIVE,Since the invoice is not posted for more than ...,455.0,1,Orissa,NaN,508434
26981,911001060286,9110 0106 0286,WESCOIND,INACTIVE,Since the invoice is not posted for more than ...,547.0,1,Orissa,NaN,454203

In [16]:
issue_acc_final= issue_acc[(issue_acc.Detailed != 'nil')]
issue_acc_final

,Normalized Account Number,Account Number,Provider Alias,Monitoring Status,Detailed,Detailed Status,Lapsed Days,Unnamed: 7,CircleName,CNBD 2,Site Code
55,1210749222,1210749222,BangaloreElectricitySupplyCoIND,INACTIVE,Since the invoice is not posted for more than ...,Since the invoice is not posted for more than ...,589.0,1,Karnataka,9794689077,588720
190,1867207000,1867207000,BangaloreElectricitySupplyCoIND,INACTIVE,Since the invoice is not posted for more than ...,Since the invoice is not posted for more than ...,148.0,1,Karnataka,1867207000,551605
191,1881365201,1881365201,BangaloreElectricitySupplyCoIND,INACTIVE,Since the invoice is not posted for more than ...,Since the invoice is not posted for more than ...,601.0,1,Karnataka,1341011564,585096
303,2151207000,2151207000,BangaloreElectricitySupplyCoIND,INACTIVE,Since the invoice is not posted for more than ...,Since the invoice is not posted for more than ...,140.0,1,Karnataka,2151207000,551054
314,2174996000,2174996000,BangaloreElectricitySupplyCoIND,INACTIVE,Since the invoice is not posted for more than ...,Since the invoice is not posted for more than ...,148.0,1,Karnataka,2174996000,550465
...,...,...,...,...,...,...,...,...,...,...,...
26744,813001110327,813001110327,TPWODLIND,INACTIVE,Since the invoice is not posted for more than ...,Since the invoice is not posted for more than ...,199.0,1,Orissa,NaN,568983
26753,813001110378,813001110378,TPWODLIND,INACTIVE,Since the invoice is not posted for more than ...,Since the invoice is not posted for more than ...,199.0,1,Orissa,NaN,453636
26762,813001110468,813001110468,TPWODLIND,INACTIVE,Since the invoice is not posted for more than ...,Since the invoice is not posted for more than ...,199.0,1,Orissa,NaN,571767
26980,416001110318,4160 0111 0318,WESCOIND,INACTIVE,Since the invoice is not posted for more than ...,Since the invoice is not posted for more than ...,455.0,1,Orissa,NaN,508434
26981,911001060286,9110 0106 0286,WESCOIND,INACTIVE,Since the invoice is not posted for more than ...,Since the invoice is not posted for more than ...,547.0,1,Orissa,NaN,454203

### Delivery failures

In [17]:
del_fail_sheet = pd.read_excel('OCT Json.xlsx',sheet_name=0)
del_fail_sheet

,Date,StatementId,AccountNumber,ProviderAlias,Circle,SiteCode,Statementdate,DeliveryResult,ResponseCode,ResponseBody,Unnamed: 10,Unnamed: 11,Unnamed: 12
0,01.10.2021,1ec219b16a0fdee3902e0e0e0c7755cb,N3281003785,MPPaschimKshetraVidyutVitaranCoIND,MadhyaPradesh,462477,2021-09-29,NOT_WANTED_API_REJECTED,400,"{""message"":""No EB Master found for SiteId/Cons...",code:400,"type:""ERROR""","details:""No Match on Consumer Number: CLZ49 - ..."
1,01.10.2021,1ec219ce3bb4dbe0aa550e879db8526d,172028463265,MaharashtraStateElectricityDistributionIND,Maharashtra,587476,2021-09-29,NOT_WANTED_API_REJECTED,400,"{""message"":""No EB Master defined for SiteId""",code:400,"type:""ERROR""","details:""SiteId: 587476""}'"
2,01.10.2021,1ec219f41720d244a4a70e0e0c7755cb,N3602009126,MPPaschimKshetraVidyutVitaranCoIND,MadhyaPradesh,461793,2021-09-29,NOT_WANTED_API_REJECTED,400,"{""message"":""No EB Master found for SiteId/Cons...",code:400,"type:""ERROR""","details:""No Match on Consumer Number: BDD26-34..."
3,01.10.2021,1ec21b04668bd2b3a5960e879db8526d,N3973003843,MPPaschimKshetraVidyutVitaranCoIND,MadhyaPradesh,451157,2021-09-29,NOT_WANTED_API_REJECTED,400,"{""message"":""No EB Master found for SiteId/Cons...",code:400,"type:""ERROR""","details:""No Match on Consumer Number: MSZ22 - ..."
4,01.10.2021,1ec21d21e472d356ab040e2894c154fd,N3962028143,MPPaschimKshetraVidyutVitaranCoIND,MadhyaPradesh,557430,2021-09-28,NOT_WANTED_API_REJECTED,400,"{""message"":""No EB Master found for SiteId/Cons...",code:400,"type:""ERROR""","details:""No Match on Consumer Number: MLZ84 - ..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...
3589,29.10.2021,1ec3825fe65ed9d197a20e15626d9e8f,5172016695,TamilNaduElectricityBoardIND,TamilNadu,590567,2021-10-28,NOT_WANTED_API_REJECTED,400,"{""message"":""No EB Master found for SiteId/Cons...",code:400,"type:""ERROR""","details:""No Match on Consumer Number: 05172016..."
3590,29.10.2021,1ec382a56b5fd5bb87d10edda61bcaa7,N3688011387,MPPaschimKshetraVidyutVitaranCoIND,MadhyaPradesh,558127,2021-10-28,NOT_WANTED_API_REJECTED,400,"{""message"":""No EB Master found for SiteId/Cons...",code:400,"type:""ERROR""","details:""No Match on Consumer Number: Ã¯Â¿Â½34246..."
3591,29.10.2021,1ec382e3e91ddb31807d0e0b6aa255cd,72380057280,TamilNaduElectricityBoardIND,TamilNadu,587295,2021-10-28,NOT_WANTED_API_REJECTED,400,"{""message"":""No EB Master defined for SiteId""",code:400,"type:""ERROR""","details:""SiteId: 587295""}"
3592,29.10.2021,1ec383996413d5f4be890e15626d9e8f,323-289-003*5,TheBrihanmumbaiElectricSupplyAndTransportIND,Mumbai,592227,2021-10-28,NOT_WANTED_API_REJECTED,400,"{""message"":""No EB Master found for SiteId/Cons...",code:400,"type:""ERROR""","details:""No Match on Consumer Number: 32328900..."
3593,29.10.2021,1ec383f6a311d823be890e15626d9e8f,799-437-063*2,TheBrihanmumbaiElectricSupplyAndTransportIND,Mumbai,567608,2021-10-28,NOT_WANTED_API_REJECTED,400,"{""message"":""No EB Master found for SiteId/Cons...",code:400,"type:""ERROR""","details:""No Match on Consumer Number: 799-437-..."

In [49]:
del_fail_sheet["Statementdate"] = pd.to_datetime(del_fail_sheet["Statementdate"])  
date_range = (del_fail_sheet["Statementdate"] >= "2021-10-01") & (del_fail_sheet["Statementdate"] <= "2021-10-29") & (del_fail_sheet["Date"] >= "01.10.2021") & (del_fail_sheet["Date"] <= "29.10.2021")
temp_df1=del_fail_sheet.loc[date_range]
del_fail_final = temp_df1[['Date','StatementId','AccountNumber','ProviderAlias','Circle','SiteCode','Statementdate','DeliveryResult','ResponseCode','ResponseBody']]
del_fail_final

,Date,StatementId,AccountNumber,ProviderAlias,Circle,SiteCode,Statementdate,DeliveryResult,ResponseCode,ResponseBody
19,01.10.2021,1ec21e2e51e3d3b29e9f0e0f977cb1e5,60005671684,GoaElectricityDeptIND,Maharashtra,461363,2021-10-01,NOT_WANTED_API_REJECTED,400,"{""message"":""No EB Master found for SiteId/Cons..."
20,01.10.2021,1ec21e36493ed6f19e9f0e0f977cb1e5,60002942351,GoaElectricityDeptIND,Maharashtra,567022,2021-10-01,NOT_WANTED_API_DUPLICATE,409,"{""message"":""EB Feed details already exists - S..."
124,04.10.2021,1ec22c05e889dfb291fa0e3afc394ba3,B612247431,GulbargaElectricitySupplyCompanyIND,Karnataka,580799,2021-10-01,NOT_WANTED_API_REJECTED,400,"{""message"":""No EB Master found for SiteId/Cons..."
125,04.10.2021,1ec22c0687fbddba91fa0e3afc394ba3,B526248876,GulbargaElectricitySupplyCompanyIND,Karnataka,524030,2021-10-01,NOT_WANTED_API_REJECTED,400,"{""message"":""No EB Master found for SiteId/Cons..."
131,04.10.2021,1ec22ce0e5c7d3f5989c0edcfb1d6363,B725319852,GulbargaElectricitySupplyCompanyIND,Karnataka,500218,2021-10-03,NOT_WANTED_API_REJECTED,400,"{""message"":""No EB Master found for SiteId/Cons..."
...,...,...,...,...,...,...,...,...,...,...
3589,29.10.2021,1ec3825fe65ed9d197a20e15626d9e8f,5172016695,TamilNaduElectricityBoardIND,TamilNadu,590567,2021-10-28,NOT_WANTED_API_REJECTED,400,"{""message"":""No EB Master found for SiteId/Cons..."
3590,29.10.2021,1ec382a56b5fd5bb87d10edda61bcaa7,N3688011387,MPPaschimKshetraVidyutVitaranCoIND,MadhyaPradesh,558127,2021-10-28,NOT_WANTED_API_REJECTED,400,"{""message"":""No EB Master found for SiteId/Cons..."
3591,29.10.2021,1ec382e3e91ddb31807d0e0b6aa255cd,72380057280,TamilNaduElectricityBoardIND,TamilNadu,587295,2021-10-28,NOT_WANTED_API_REJECTED,400,"{""message"":""No EB Master defined for SiteId"""
3592,29.10.2021,1ec383996413d5f4be890e15626d9e8f,323-289-003*5,TheBrihanmumbaiElectricSupplyAndTransportIND,Mumbai,592227,2021-10-28,NOT_WANTED_API_REJECTED,400,"{""message"":""No EB Master found for SiteId/Cons..."
3593,29.10.2021,1ec383f6a311d823be890e15626d9e8f,799-437-063*2,TheBrihanmumbaiElectricSupplyAndTransportIND,Mumbai,567608,2021-10-28,NOT_WANTED_API_REJECTED,400,"{""message"":""No EB Master found for SiteId/Cons..."

In [50]:
del_fail_pivot = pd.pivot_table(del_fail_final, values='StatementId', index=['Circle','ProviderAlias'],
                    aggfunc={'StatementId': ['count']})
del_fail_pivot

                                                            count
Circle        ProviderAlias
AndhraPradesh EPDCAPIND                                        94
Chhattisgarh  ChhattisgarhStatePowerDistributionCOIND          93
Karnataka     BangaloreElectricitySupplyCoIND                  12
              ChamundeshwariElectricitySupplyCorpIND           10
              GulbargaElectricitySupplyCompanyIND              22
              HubliElectricitySupplyCoIND                      12
Kerala        KSEBIND                                          81
MadhyaPradesh MPMadhyaKshetraVidyutVitaranCoIND               811
              MPPaschimKshetraVidyutVitaranCoIND              247
              MPPoorvKshetraVidyutVitaranIND                 1530
Maharashtra   GoaElectricityDeptIND                            21
              MaharashtraStateElectricityDistributionIND       90
              TorrentPowerLimitedIND                           16
Mumbai        MaharashtraStateElectricityDistributionIND       51
              TataPowerIND                                      1
              TheBrihanmumbaiElectricSupplyAndTransportIND     31
              TorrentPowerLimitedIND                           17
Orissa        TPCODLIND                                         6
              TPNODLIND                                        57
              TPSODLIND                                         2
              TPWODLIND                                       145
TamilNadu     TamilNaduElectricityBoardIND                     54

In [51]:
del_fail_pivot['count'].sum()

3403

In [25]:
cust_data = pd.read_csv('ebfeed_dump.csv')
cust_data

D:\anaconda\lib\site-packages\IPython\core\interactiveshell.py:3165: DtypeWarning: Columns (61) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,

,Site ID,Consumer ID,Meter No (KWH),Old Account No,Knumber,Phase,Sanctioned Load,Meter Status,Tariff,Board Name,...,FeedStatus,Transformer Loss Unit,Rebate Unit,Penalty Units,Total Units,Circle,Unnamed: 147,Unnamed: 148,Unnamed: 149,Unnamed: 150
0,509207,065630091131,1592002,NaN,NaN,THREE,15.00,NORMAL,LM51,TamilNaduElectricityBoardIND,...,NEW,-,-,-,"5,250",IND Tamilnadu,NaN,NaN,NaN,NaN
1,549682,2355223000,6408557721,NaN,NaN,NaN,18.00,NaN,1LT3IN,BangaloreElectricitySupplyCoIND,...,NEW,-,-,-,"1,480",IND Karnataka,NaN,NaN,NaN,NaN
2,462389,TNZ51 - 17 - 3376027613,GENUS3915200,IT51 - 17 - 7408124000,NaN,THREE,16.00,NORMAL,LV2.2,MPPaschimKshetraVidyutVitaranCoIND,...,NEW,-,-,-,0,IND Madhya Pradesh,NaN,NaN,NaN,NaN
3,591742,160263887473,08806766415,NaN,4613,NaN,3.00,NaN,052 / LT-II COMM < 20KW,MaharashtraStateElectricityDistributionIND,...,VALIDATED,-,-,-,"1,929",IND Maharashtra,NaN,NaN,NaN,NaN
4,462452,3615105-GHS11-2-N3105008765,SECUREMPP20902,11-2-83227,NaN,THREE,16.00,NORMAL,LV2.2,MPPaschimKshetraVidyutVitaranCoIND,...,NEW,-,-,-,"5,091",IND Madhya Pradesh,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
23131,530846,3634415-TNL1-30-N3435022400,SECUREMPP30859,1 - 30 - 7481,NaN,THREE,15.00,NORMAL,LV2.2,MPPaschimKshetraVidyutVitaranCoIND,...,NEW,-,-,-,"3,943",IND Madhya Pradesh,NaN,NaN,NaN,NaN
23132,461238,3363302-NLT95-50-N3332007082,AVON3089407,95 - 50 - 120455,NaN,THREE,15.00,NORMAL,LV2.2,MPPaschimKshetraVidyutVitaranCoIND,...,NEW,-,-,-,"1,990",IND Madhya Pradesh,NaN,NaN,NaN,NaN
23133,570633,3634408-MGN1-4-N3428028882,GENUS9015717,1 - 4 - 3440,NaN,THREE,15.00,NORMAL,LV2.2,MPPaschimKshetraVidyutVitaranCoIND,...,NEW,-,-,-,"4,603",IND Madhya Pradesh,NaN,NaN,NaN,NaN
23134,544954,1165172026491,L+G065170004961581,NaN,NaN,THREE,8.22,Working,LT-6F,KSEBIND,...,NEW,-,-,-,"2,920",IND Kerala,NaN,NaN,NaN,NaN
23135,545763,1166644020360,L&T001860018327073,NaN,NaN,THREE,15.89,Working,LT-6F,KSEBIND,...,NEW,-,-,-,0,IND Kerala,NaN,NaN,NaN,NaN

In [26]:
cust_data["Concatenate"]=cust_data["Board Name"]+'-'+cust_data["Site ID"].astype(str)
cust_data

,Site ID,Consumer ID,Meter No (KWH),Old Account No,Knumber,Phase,Sanctioned Load,Meter Status,Tariff,Board Name,...,Transformer Loss Unit,Rebate Unit,Penalty Units,Total Units,Circle,Unnamed: 147,Unnamed: 148,Unnamed: 149,Unnamed: 150,Concatenate
0,509207,065630091131,1592002,NaN,NaN,THREE,15.00,NORMAL,LM51,TamilNaduElectricityBoardIND,...,-,-,-,"5,250",IND Tamilnadu,NaN,NaN,NaN,NaN,TamilNaduElectricityBoardIND-509207
1,549682,2355223000,6408557721,NaN,NaN,NaN,18.00,NaN,1LT3IN,BangaloreElectricitySupplyCoIND,...,-,-,-,"1,480",IND Karnataka,NaN,NaN,NaN,NaN,BangaloreElectricitySupplyCoIND-549682
2,462389,TNZ51 - 17 - 3376027613,GENUS3915200,IT51 - 17 - 7408124000,NaN,THREE,16.00,NORMAL,LV2.2,MPPaschimKshetraVidyutVitaranCoIND,...,-,-,-,0,IND Madhya Pradesh,NaN,NaN,NaN,NaN,MPPaschimKshetraVidyutVitaranCoIND-462389
3,591742,160263887473,08806766415,NaN,4613,NaN,3.00,NaN,052 / LT-II COMM < 20KW,MaharashtraStateElectricityDistributionIND,...,-,-,-,"1,929",IND Maharashtra,NaN,NaN,NaN,NaN,MaharashtraStateElectricityDistributionIND-591742
4,462452,3615105-GHS11-2-N3105008765,SECUREMPP20902,11-2-83227,NaN,THREE,16.00,NORMAL,LV2.2,MPPaschimKshetraVidyutVitaranCoIND,...,-,-,-,"5,091",IND Madhya Pradesh,NaN,NaN,NaN,NaN,MPPaschimKshetraVidyutVitaranCoIND-462452
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
23131,530846,3634415-TNL1-30-N3435022400,SECUREMPP30859,1 - 30 - 7481,NaN,THREE,15.00,NORMAL,LV2.2,MPPaschimKshetraVidyutVitaranCoIND,...,-,-,-,"3,943",IND Madhya Pradesh,NaN,NaN,NaN,NaN,MPPaschimKshetraVidyutVitaranCoIND-530846
23132,461238,3363302-NLT95-50-N3332007082,AVON3089407,95 - 50 - 120455,NaN,THREE,15.00,NORMAL,LV2.2,MPPaschimKshetraVidyutVitaranCoIND,...,-,-,-,"1,990",IND Madhya Pradesh,NaN,NaN,NaN,NaN,MPPaschimKshetraVidyutVitaranCoIND-461238
23133,570633,3634408-MGN1-4-N3428028882,GENUS9015717,1 - 4 - 3440,NaN,THREE,15.00,NORMAL,LV2.2,MPPaschimKshetraVidyutVitaranCoIND,...,-,-,-,"4,603",IND Madhya Pradesh,NaN,NaN,NaN,NaN,MPPaschimKshetraVidyutVitaranCoIND-570633
23134,544954,1165172026491,L+G065170004961581,NaN,NaN,THREE,8.22,Working,LT-6F,KSEBIND,...,-,-,-,"2,920",IND Kerala,NaN,NaN,NaN,NaN,KSEBIND-544954
23135,545763,1166644020360,L&T001860018327073,NaN,NaN,THREE,15.89,Working,LT-6F,KSEBIND,...,-,-,-,0,IND Kerala,NaN,NaN,NaN,NaN,KSEBIND-545763

In [55]:
cust_data["Bill Issue Date"] = pd.to_datetime(cust_data["Bill Issue Date"])  
date_range = (cust_data["Bill Issue Date"] >= "2021-10-01") & (cust_data["Bill Issue Date"] <= "2021-11-01")
cust_data_final=cust_data.loc[date_range]
cust_data_final
final_cust_df = cust_data_final[['Site ID','Consumer ID','Board Name','Bill Issue Date','Created Date','Circle','Concatenate']]
final_cust_df

,Site ID,Consumer ID,Board Name,Bill Issue Date,Created Date,Circle,Concatenate
292,566751,60000605570,GoaElectricityDeptIND,2021-10-01,2021-09-27,IND Maharashtra,GoaElectricityDeptIND-566751
595,566242,60004637637,GoaElectricityDeptIND,2021-10-01,2021-09-28,IND Maharashtra,GoaElectricityDeptIND-566242
738,461325,60002942427,GoaElectricityDeptIND,2021-10-01,2021-09-29,IND Maharashtra,GoaElectricityDeptIND-461325
1054,567022,60002942351,GoaElectricityDeptIND,2021-10-01,2021-09-30,IND Maharashtra,GoaElectricityDeptIND-567022
1060,461349,60003470915,GoaElectricityDeptIND,2021-10-04,2021-09-30,IND Maharashtra,GoaElectricityDeptIND-461349
...,...,...,...,...,...,...,...
23131,530846,3634415-TNL1-30-N3435022400,MPPaschimKshetraVidyutVitaranCoIND,2021-10-28,2021-10-29,IND Madhya Pradesh,MPPaschimKshetraVidyutVitaranCoIND-530846
23132,461238,3363302-NLT95-50-N3332007082,MPPaschimKshetraVidyutVitaranCoIND,2021-10-28,2021-10-29,IND Madhya Pradesh,MPPaschimKshetraVidyutVitaranCoIND-461238
23133,570633,3634408-MGN1-4-N3428028882,MPPaschimKshetraVidyutVitaranCoIND,2021-10-28,2021-10-29,IND Madhya Pradesh,MPPaschimKshetraVidyutVitaranCoIND-570633
23134,544954,1165172026491,KSEBIND,2021-10-28,2021-10-29,IND Kerala,KSEBIND-544954
23135,545763,1166644020360,KSEBIND,2021-10-28,2021-10-29,IND Kerala,KSEBIND-545763

In [56]:
cust_acc_table_final = pd.pivot_table(final_cust_df, values='Site ID', index=['Circle','Board Name'],
                    aggfunc={'Site ID': ['count','nunique']})
cust_acc_table_final

                                                                 count  \
Circle             Board Name
IND Andhra Pradesh EPDCAPIND                                       506
IND Karnataka      BangaloreElectricitySupplyCoIND                2059
                   ChamundeshwariElectricitySupplyCorpIND          240
                   GulbargaElectricitySupplyCompanyIND             307
                   HubliElectricitySupplyCoIND                     506
                   MangaloreElectricitySupplyCOIND                 211
IND Kerala         KSEBIND                                        1695
IND Madhya Pradesh ChhattisgarhStatePowerDistributionCOIND        1688
                   MPMadhyaKshetraVidyutVitaranCoIND              1416
                   MPPaschimKshetraVidyutVitaranCoIND             1360
                   MPPoorvKshetraVidyutVitaranIND                  341
IND Maharashtra    GoaElectricityDeptIND                           100
                   MaharashtraStateElectricityDistributionIND     5812
                   TorrentPowerLimitedIND                           53
IND Mumbai Circle  KSEBIND                                           1
                   MaharashtraStateElectricityDistributionIND      561
                   TataPowerIND                                     13
                   TheBrihanmumbaiElectricSupplyAndTransportIND    172
                   TorrentPowerLimitedIND                           41
IND Orissa         TPCODLIND                                      1389
                   TPNODLIND                                       773
                   TPSODLIND                                       395
                   TPWODLIND                                       586
IND Tamilnadu      TamilNaduElectricityBoardIND                   1364

                                                                 nunique
Circle             Board Name
IND Andhra Pradesh EPDCAPIND                                         502
IND Karnataka      BangaloreElectricitySupplyCoIND                  2033
                   ChamundeshwariElectricitySupplyCorpIND            235
                   GulbargaElectricitySupplyCompanyIND               301
                   HubliElectricitySupplyCoIND                       497
                   MangaloreElectricitySupplyCOIND                   206
IND Kerala         KSEBIND                                          1692
IND Madhya Pradesh ChhattisgarhStatePowerDistributionCOIND          1651
                   MPMadhyaKshetraVidyutVitaranCoIND                1380
                   MPPaschimKshetraVidyutVitaranCoIND               1335
                   MPPoorvKshetraVidyutVitaranIND                    334
IND Maharashtra    GoaElectricityDeptIND                              98
                   MaharashtraStateElectricityDistributionIND       5812
                   TorrentPowerLimitedIND                             53
IND Mumbai Circle  KSEBIND                                             1
                   MaharashtraStateElectricityDistributionIND        561
                   TataPowerIND                                       13
                   TheBrihanmumbaiElectricSupplyAndTransportIND      172
                   TorrentPowerLimitedIND                             41
IND Orissa         TPCODLIND                                        1372
                   TPNODLIND                                         773
                   TPSODLIND                                         395
                   TPWODLIND                                         586
IND Tamilnadu      TamilNaduElectricityBoardIND                     1363

In [57]:
cust_acc_table_final.rename(columns = {'count':'All',
                                        'nunique':'Unique'}, inplace = True)
cust_acc_table_final

                                                                  All  Unique
Circle             Board Name
IND Andhra Pradesh EPDCAPIND                                      506     502
IND Karnataka      BangaloreElectricitySupplyCoIND               2059    2033
                   ChamundeshwariElectricitySupplyCorpIND         240     235
                   GulbargaElectricitySupplyCompanyIND            307     301
                   HubliElectricitySupplyCoIND                    506     497
                   MangaloreElectricitySupplyCOIND                211     206
IND Kerala         KSEBIND                                       1695    1692
IND Madhya Pradesh ChhattisgarhStatePowerDistributionCOIND       1688    1651
                   MPMadhyaKshetraVidyutVitaranCoIND             1416    1380
                   MPPaschimKshetraVidyutVitaranCoIND            1360    1335
                   MPPoorvKshetraVidyutVitaranIND                 341     334
IND Maharashtra    GoaElectricityDeptIND                          100      98
                   MaharashtraStateElectricityDistributionIND    5812    5812
                   TorrentPowerLimitedIND                          53      53
IND Mumbai Circle  KSEBIND                                          1       1
                   MaharashtraStateElectricityDistributionIND     561     561
                   TataPowerIND                                    13      13
                   TheBrihanmumbaiElectricSupplyAndTransportIND   172     172
                   TorrentPowerLimitedIND                          41      41
IND Orissa         TPCODLIND                                     1389    1372
                   TPNODLIND                                      773     773
                   TPSODLIND                                      395     395
                   TPWODLIND                                      586     586
IND Tamilnadu      TamilNaduElectricityBoardIND                  1364    1363

In [58]:
cust_acc_table_final['All'].sum()

21589

In [59]:
cust_acc_table_final['Unique'].sum()

21406

In [60]:
def dfs_tabs(df_list, sheet_list, file_name):
    writer = pd.ExcelWriter(file_name,engine='xlsxwriter')   
    for dataframe, sheet in zip(df_list, sheet_list):
        dataframe.to_excel(writer, sheet_name=sheet, startrow=0 , startcol=0)   
    writer.save()


dfs = [issue_acc_final,del_fail_final,del_fail_pivot,final_cust_df,cust_acc_table_final]
sheets = ['Accounts with issues','Delivery Failures',
          'delivery_failures_pivot','Customer portal accounts','cust_acc_portal_pivot']    


dfs_tabs(dfs, sheets, 'Final file using python.xlsx')

In [ ]:
# delivery failures only for this month from oct json - Done
# get data from ebfeed file (only the columns in cust portal acc file for month of october) - Done
# big work (update for each circle seperately)
# detailed status on basis of monitoring status 
# aged bill are lapsed days greater than 45 (automate this)
# reason of failure in dashboard to be updated acc to delivery failure count
# import these dataframes in excel and then vlookup - Done

#accounts with issues from master data remove -- from detailed status column - Done
# new delivery failures count is 3403 - Correct

# new unique and all counts 21406 21589 - Correct

In [3]:
del_fail_sheet = pd.read_excel('NOV Json.xlsx',sheet_name=0)
del_fail_sheet

,Date,Delivered Date,StatementId,AccountNumber,ProviderAlias,Circle,SiteCode,Statementdate,DeliveryResult,ResponseCode,ResponseBody,Unnamed: 11,Unnamed: 12,Unnamed: 13
0,29.10.2021,11.01.2021,1ec38742b6dcdb1093480edda61bcaa7,334220184,MaharashtraStateElectricityDistributionIND,Mumbai,578445,2021-10-28,NOT_WANTED_API_REJECTED,400,"{""message"":""No EB Master found for SiteId/Cons...",code:400,"type:""ERROR""","details:""No Match on Consumer Number: 00033422..."
1,29.10.2021,11.01.2021,1ec3876f8568d9be93480edda61bcaa7,334291057,MaharashtraStateElectricityDistributionIND,Mumbai,587428,2021-10-28,NOT_WANTED_API_REJECTED,400,"{""message"":""No EB Master defined for SiteId""",code:400,"type:""ERROR""","details:""SiteId: 587428""}"
2,29.10.2021,11.01.2021,1ec388fa4511da2fac0c0e0b6aa255cd,904-624-602*3,TheBrihanmumbaiElectricSupplyAndTransportIND,Mumbai,531202,2021-10-29,NOT_WANTED_API_REJECTED,400,"{""message"":""No EB Master found for SiteId/Cons...",code:400,"type:""ERROR""","details:""No Match on Consumer Number: 904624602""}"
3,29.10.2021,11.01.2021,1ec388ffe50ad704ac0c0e0b6aa255cd,908-802-815*9,TheBrihanmumbaiElectricSupplyAndTransportIND,Mumbai,451653,2021-10-29,NOT_WANTED_API_REJECTED,400,"{""message"":""No EB Master found for SiteId/Cons...",code:400,"type:""ERROR""","details:""No Match on Consumer Number: 90880281..."
4,29.10.2021,11.01.2021,1ec389029091d63eac0c0e0b6aa255cd,504-302-971*8,TheBrihanmumbaiElectricSupplyAndTransportIND,Mumbai,451607,2021-10-29,NOT_WANTED_API_REJECTED,400,"{""message"":""No EB Master found for SiteId/Cons...",code:400,"type:""ERROR""","details:""No Match on Consumer Number: 50430297..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
151,04.11.2021,05.11.2021,1ec3d7eb22cdd943a5ae0eadeb41f489,'1123120000352318',EPDCAPIND,AndhraPradesh,526278,2021-11-03,NOT_WANTED_API_REJECTED,400,"{""message"":""No EB Master found for SiteId/Cons...",code:400,"type:""ERROR""","details:""No Match on Consumer Number: \""112312..."
152,04.11.2021,05.11.2021,1ec3d8cade0fd6dfa9620e8b1d5dfd17,170019082710,MaharashtraStateElectricityDistributionIND,Maharashtra,566466,2021-11-04,NOT_WANTED_API_REJECTED,400,"{""message"":""No EB Master found for SiteId/Cons...",code:400,"type:""ERROR""","details:""No Match on Consumer Number: 17001908..."
153,04.11.2021,05.11.2021,1ec3dcf76873d63fb0040ee30344f117,1145212033461,KSEBIND,Kerala,582449,2021-11-01,NOT_WANTED_API_REJECTED,400,"{""message"":""No EB Master found for SiteId/Cons...",code:400,"type:""ERROR""","details:""No Match on Consumer Number: 33461""}'"
154,04.11.2021,05.11.2021,1ec3dd3ab5a5d393a93e0ee30344f117,1156740017606,KSEBIND,Kerala,591368,2021-11-01,NOT_WANTED_API_REJECTED,404,"{""message"":""site with id 591368 not found""",code:404,"type:""ERROR""",details:null}'
155,04.11.2021,05.11.2021,1ec3dd9475e1db83bbce0ee30344f117,1155390015884,KSEBIND,Kerala,588006,2021-11-01,NOT_WANTED_API_REJECTED,404,"{""message"":""site with id 588006 not found""",code:404,"type:""ERROR""",details:null}'

In [9]:
del_fail_sheet["Statementdate"] = pd.to_datetime(del_fail_sheet["Statementdate"])  
date_range = (del_fail_sheet["Statementdate"] >= "2021-11-01") & (del_fail_sheet["Statementdate"] <= "2021-11-05")
temp_df1=del_fail_sheet.loc[date_range]
del_fail_final = temp_df1[['Date','StatementId','AccountNumber','ProviderAlias','Circle','SiteCode','Statementdate','DeliveryResult','ResponseCode','ResponseBody']]
del_fail_final

,Date,StatementId,AccountNumber,ProviderAlias,Circle,SiteCode,Statementdate,DeliveryResult,ResponseCode,ResponseBody
63,01.11.2021,1ec3b11bb407d902b37f0e728a91b853,B612247431,GulbargaElectricitySupplyCompanyIND,Karnataka,580799,2021-11-01,NOT_WANTED_API_REJECTED,400,"{""message"":""No EB Master found for SiteId/Cons..."
64,01.11.2021,1ec3b71d4e6ede6688ae0e57ecc54a1b,1145935032420,KSEBIND,Kerala,595518,2021-11-01,NOT_WANTED_API_REJECTED,404,"{""message"":""site with id 595518 not found"""
65,01.11.2021,1ec3b72df168dbddaa3d0e57ecc54a1b,1156633024404,KSEBIND,Kerala,506690,2021-11-01,NOT_WANTED_API_REJECTED,400,"{""message"":""No EB Master found for SiteId/Cons..."
66,01.11.2021,1ec3b74b76a1d395aa3d0e57ecc54a1b,1145551029617,KSEBIND,Kerala,587947,2021-11-01,NOT_WANTED_API_REJECTED,404,"{""message"":""site with id 587947 not found"""
67,01.11.2021,1ec3b77d4bbfdf4788ae0e57ecc54a1b,1145029020511,KSEBIND,Kerala,593808,2021-11-01,NOT_WANTED_API_REJECTED,404,"{""message"":""site with id 593808 not found"""
...,...,...,...,...,...,...,...,...,...,...
151,04.11.2021,1ec3d7eb22cdd943a5ae0eadeb41f489,'1123120000352318',EPDCAPIND,AndhraPradesh,526278,2021-11-03,NOT_WANTED_API_REJECTED,400,"{""message"":""No EB Master found for SiteId/Cons..."
152,04.11.2021,1ec3d8cade0fd6dfa9620e8b1d5dfd17,170019082710,MaharashtraStateElectricityDistributionIND,Maharashtra,566466,2021-11-04,NOT_WANTED_API_REJECTED,400,"{""message"":""No EB Master found for SiteId/Cons..."
153,04.11.2021,1ec3dcf76873d63fb0040ee30344f117,1145212033461,KSEBIND,Kerala,582449,2021-11-01,NOT_WANTED_API_REJECTED,400,"{""message"":""No EB Master found for SiteId/Cons..."
154,04.11.2021,1ec3dd3ab5a5d393a93e0ee30344f117,1156740017606,KSEBIND,Kerala,591368,2021-11-01,NOT_WANTED_API_REJECTED,404,"{""message"":""site with id 591368 not found"""
155,04.11.2021,1ec3dd9475e1db83bbce0ee30344f117,1155390015884,KSEBIND,Kerala,588006,2021-11-01,NOT_WANTED_API_REJECTED,404,"{""message"":""site with id 588006 not found"""